name: Deploy Dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Prepare /dev folder
        run: |
          mkdir dev
          cp -R * dev
          rm -f dev/CNAME


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dev

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
